spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: prod!

management:
  metrics:
    export:
      elastic:
        enabled: true
        host: "http://elasticsearch:9200"
        index: micrometer
        auto-create-index: true
        step: 10s
        distribution:
          percentiles-histogram:
            http:
              server:
                requests: true
          sla:
            http:
              server:
                requests: 100ms, 400ms, 500ms, 2000ms
          percentiles:
            http:
              server:
                requests: 0.5, 0.75, 0.95, 0.99