ARG LOGSTASH_FILEBEAT_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${LOGSTASH_FILEBEAT_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
